### ISSUE TITLE
Samples at "Adobe DevNet" fail to run

### ISSUE THREAD

**Issue by waddlesplash** [mozilla/shumway#135]
**Drawing samples**
- [ ] Coordinate space, radians, and degrees - [[original](http://www.adobe.com/devnet/actionscript/samples/drawing_1.edu.html)] [[archived](http://swf.codeazur.com.br/#8b4659c92ec6915b94ff9ff8f69076538f47aa83253b7ecd8941f9b92a9e6c31)] - _Sprite::startDrag() not implemented. TextInput component doesn't work._
- [ ] 3D rotation - [[original](http://www.adobe.com/devnet/actionscript/samples/drawing_5.html)] [[archived](http://swf.codeazur.com.br/#4d2489dfc502c54613a68b441326cd32a6e0f5373d900c019cb46619b3edab81)] - _DisplayObject::rotationX/Y/Z not implemented._
- [ ] Movie clip nesting - [[original](http://www.adobe.com/devnet/actionscript/samples/drawing_2.html)] [[archived](http://swf.codeazur.com.br/#34bc4b52eeb49e4599bbdc4ad9974500e9acf60f66a4f99c67e846e686c6481a)] - _Sprite::startDrag() not implemented. cxform not implemented._
- [ ] Patterns and advanced 3D effects - [[original](http://www.adobe.com/devnet/actionscript/samples/drawing_6.html)] [[archived](http://swf.codeazur.com.br/#1c8d44b4cd67a908ee83bf1f6ad8db20bb4aab92bff7e9ee64868bb3963e79e1)]
- [ ] Drawing API - [[original](http://www.adobe.com/devnet/actionscript/samples/drawing_3.html)] [[archived](http://swf.codeazur.com.br/#c8d0b08e97c84b2ae1851a139facac125216445a82b3af0fda412a5db2b125d0)] - _almost works now_
- [ ] Transition FX - [[original](http://www.adobe.com/devnet/actionscript/samples/drawing_7.html)] [[archived](http://swf.codeazur.com.br/#b9e7829a09ec7f5ea27f2f20bb5f05100b22d6327f24a0d007aef64179f3513e)] - _some FX work, not all_
- [x] Color transformations - [[original](http://www.adobe.com/devnet/actionscript/samples/drawing_4.html)] [[archived](http://swf.codeazur.com.br/#274af0e510d9805e156c3f1d6976f6b766eeab998133eb94e82b09c7661e975d)]

**Media samples**
- [ ] Dynamic text - [[original](http://www.adobe.com/devnet/actionscript/samples/media_1.html)] [[archived](http://swf.codeazur.com.br/#b31396822c4213b60e32cfa58d23c02b7370742eb63416da9257cc421d5ecd67)]
- [ ] Sound channels - [[original](http://www.adobe.com/devnet/actionscript/samples/media_5.html)] [[archived](http://swf.codeazur.com.br/#49996176d7c2977eb7efda9a4ace0e80ce69f11d9847e866afb2fd32f87e3196)]
- [ ] Image loading - [[original](http://www.adobe.com/devnet/actionscript/samples/media_2.html)] [[archived](http://swf.codeazur.com.br/#020ed4d7186c95ca2c0745a7856adb16b39c7da0e85cf310c604e1471fd23a98)]
- [ ] Dynamic sound generation - [[original](http://www.adobe.com/devnet/actionscript/samples/media_6.html)] [[archived](http://swf.codeazur.com.br/#671b8b642c12b764215ebc5ebddc950b4b3222888b97708bdad40dd7c6f770cc)]
- [ ] Image masking - [[original](http://www.adobe.com/devnet/actionscript/samples/media_3.html)] [[archived](http://swf.codeazur.com.br/#b8d44572dbb705f43142d3b166facd5d9f914e92ccd72dba823124db8aa6aa20)] - _loads, appears to run but no masks. And ZBuffer doesn't work_
- [ ] Classic text formatting - [[original](http://www.adobe.com/devnet/actionscript/samples/media_7.html)] [[archived](http://swf.codeazur.com.br/#b963fa56fe59da1d3d5c69236601b13742f8074abb9c5922cb0a0566430b6999)] _misses stylesheet support in TextField_
- [ ] Sound loading - [[original](http://www.adobe.com/devnet/actionscript/samples/media_4.html)] [[archived](http://swf.codeazur.com.br/#6f3e32008c193ec17b67b3498c93694c780b92c94abcbad9eefd57af7cc5a728)]
- [ ] TLF text formatting - [[original](http://www.adobe.com/devnet/actionscript/samples/media_8.html)] [[archived_1](http://swf.codeazur.com.br/#b935f32237d5344409c071ad04e04d17133debe901bdd71a845f26f8f213ce46)] [[archived_2](http://swf.codeazur.com.br/#119eabf325da4ef27e54283ddbb1fa6d3d2c1fa45b3427db1ee6ab68158f3e0d)]

**Component samples**
- [ ] Video player - [[original](http://www.adobe.com/devnet/actionscript/samples/component_1.html)] [[archived](http://swf.codeazur.com.br/#47ff9f16e09cd763e200d36f7b8473e8e3e99424c291dfc68b6bf1a5e7191858)]
- [ ] Customized buttons - [[original](http://www.adobe.com/devnet/actionscript/samples/component_2.html)] [[archived](http://swf.codeazur.com.br/#6f7891d77ec9b66d0e0384cefc059bec374a2ad070fd2c481797b7e201c9e0f9)]

**Time samples**
- [x] Stopwatch timer - [[original](http://www.adobe.com/devnet/actionscript/samples/time_1.html)] [[archived](http://swf.codeazur.com.br/#97246825e61b79e2ea82523e0562b7868ac8d326378c8fe31c63deeadb1cb4e0)]
- [x] Clock - [[original](http://www.adobe.com/devnet/actionscript/samples/time_2.html)] [[archived](http://swf.codeazur.com.br/#89d1441d6613d83f7bb626357c2b0431f3354b9632422b0ccb477bb646a145dd)]

**Interactivity samples**
- [x] Button-controlled movement - [[original](http://www.adobe.com/devnet/actionscript/samples/interactivity_1.html)] [[archived](http://swf.codeazur.com.br/#4e55dd68d6de4544c40c1c81480e5a4b2737b5441017078c251e6be2e33509ed)]
- [x] Click-controlled movement - [[original](http://www.adobe.com/devnet/actionscript/samples/interactivity_5.html)] [[archived](http://swf.codeazur.com.br/#4a0777455ae27ae7be04a3bad859a2caa0b4baa8ae6add0dbf53e136bd3cb2f7)]
- [x] Slider-controlled movement - [[original](http://www.adobe.com/devnet/actionscript/samples/interactivity_2.html)] [[archived](http://swf.codeazur.com.br/#bfdc26ad823dd0ec66ba422674183fa572559f50709eb1cc91721fb3ace239a0)]
- [x] Object thrust - [[original](http://www.adobe.com/devnet/actionscript/samples/interactivity_6.html)] [[archived](http://swf.codeazur.com.br/#8b75bdb9c54a09564eab91ed8b7d77e2e607e4d2f63ad134eacc9a5041f6ff56)]
- [x] Joystick-controlled movement - [[original](http://www.adobe.com/devnet/actionscript/samples/interactivity_3.html)] [[archived](http://swf.codeazur.com.br/#1f5f342c48eb8d1008e7fdf95f349e241d0e442bd5a5c1daec8e06b49419aefe)]
- [x] Background scrolling - [[original](http://www.adobe.com/devnet/actionscript/samples/interactivity_7.html)] [[archived](http://swf.codeazur.com.br/#2c14d447b1bb50666e6511406e654c722438ca23aac2cf564f3775ce47e4294c)] - _fully works, but labels aren't displayed_
- [x] Keyboard-controlled movement - [[original](http://www.adobe.com/devnet/actionscript/samples/interactivity_4.html)] [[archived](http://swf.codeazur.com.br/#86b07c4d9890eaf7ad02bac6ffa13cb7d9f9e2d857c424a1567eaeae81c7c4bd)]
- [x] Inverse kinematics - [[original](http://www.adobe.com/devnet/actionscript/samples/interactivity_8.html)] [[archived](http://swf.codeazur.com.br/#d4567f1402d84d9388676579f3d75dd83553fd682d0da3e9dee0674284a9b93c)] - _almost entirely correct. Text is moved far to the left._

**Game samples**
- [x] Maze game - [[original](http://www.adobe.com/devnet/actionscript/samples/game_1.html)] [[archived](http://swf.codeazur.com.br/#50648c109fb8c3e7d75c401bf622cc4cbc24bcd33c0159fd557f34e9f6af3f44)]
- [ ] Amoebae game - [[original](http://www.adobe.com/devnet/actionscript/samples/game_2.html)] [[archived](http://swf.codeazur.com.br/#2cba84b4c5109f373dbd8eb83dd1797b3244942aa9a82396e8c60bb762d1bebf)]
