### ISSUE TITLE
[Meta] Inspector features

### ISSUE THREAD

**Issue by claus** [mozilla/shumway#603]
- [ ] Summary of the number of various display objects types
- [ ] Button to invalidate and repaint the stage several times
- [ ] Editable properties of display objects
- [ ] Visualization of bounding boxes of display objects on stage, different colors for different types, click on bounding box highlights corresponding item in list and vice versa
- [ ] Visualization of display objects on stage, dim all other objects except the selected one
- [ ] Show selected display object without transforms in separate panel
- [x] Button to advance to next frame when paused
- [x] Button to mute sounds
