### ISSUE TITLE
[Meta] SWF Archive features/ issues

### ISSUE THREAD

**Issue by tschneidereit** [mozilla/shumway#778]
As discussed in meetings, there are a few changes that would make the SWF archive much more usable:
- [x] Display the name/path of the SWFs instead of the hash in the SWF list
- [x] In the SWF Scraper, make the scraping results clickable - regardless of whether they are new results or duplicates
- [x] Make entries flaggable: `to be investigated`, `fully works` and `critical`, or something similar, and enable filtering or sorting the list based on these flags

(Please add more issues as bullet points to this list)
